import localFont from "next/font/local";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Card } from "@/components/ui/card";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Card className="header-card">
          <header className="header">
            <div>
              <h1>voyage-craft</h1>
            </div>
            <div>
              <Link href={"/"}><Button>home</Button></Link>
            </div>
          </header>
        </Card>
        {children}
      </body>
      <style>{`
      .header-card {
        padding: 0.5rem;
      }

      .header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        flex-direction: row;
      }
      `}</style>
    </html>
  );
}
